trigger:
  branches:
    include:
      - main

pool:
  # name: newpool
  vmImage: 'ubuntu-latest'

stages:
  - stage: precheck
    displayName: "Terraform Validation"
    jobs:
      - job: terraformvalidate
        displayName: "Format & Validate"
        steps:
          - task: TerraformInstaller@1
            displayName: terraform install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: Terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'application-svc'
              backendAzureRmStorageAccountName: 'backendstg12354'
              backendAzureRmContainerName: 'my-container'
              backendAzureRmKey: 'raman-tfstate'
          - task: TerraformTask@5
            displayName: Terraform FMT
            inputs:
              provider: 'azurerm'
              command: 'custom'
              outputTo: 'console'
              customCommand: 'fmt'
              environmentServiceNameAzureRM: 'application-svc'
          - task: TerraformTask@5
            displayName: Terraform Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfsecurityscan
    dependsOn: precheck
    displayName: Security & Lint Scan
    jobs:           
      - job: tfsecurityscan
        displayName: Security & Lint Scan
        continueOnError: true
        steps: 
          - task: tfsec@1
            displayName: tf_sec
            inputs:
              version: 'v1.26.0'
              dir: '$(Build.SourcesDirectory)/environments/dev'

          - script: |
              terraform init -backend=false
              tflint --init
              tflint --recursive
            displayName: Run TFLint
            workingDirectory: '$(Build.SourcesDirectory)/environments/dev'
            continueOnError: true
          - script: |
              python3 -m venv venv
              source venv/bin/activate
              pip install --upgrade pip
              pip install checkov
              checkov -d .
            workingDirectory: $(Build.SourcesDirectory)
            continueOnError: true
            displayName: CHECKOV 
  - stage: infracost
    dependsOn: tfsecurityscan
    displayName: Infracost Analysis
    jobs:       
      - job: infracostanalysis
        displayName: "Infracost Analysis"
        steps:
          - script: |
              curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
              infracost breakdown --path .
            workingDirectory: $(Build.SourcesDirectory)
            displayName: Infracost
            continueOnError: true
            env:
              INFRACOST_API_KEY: 'ico-ofRGrUGe9ncyiu9H0xRdqMsjihpJoXBl'
  - stage: terraformplan
    displayName: Terraform Plan
    dependsOn: infracost
    jobs:
      - job: terraformplan
        displayName: Terraform Plan
        steps:
          - task: TerraformInstaller@1
            displayName: Terraform install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: Terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
              backendAzureRmStorageAccountName: 'backendstg12354'
              backendAzureRmContainerName: 'my-container'
              backendAzureRmKey: 'raman-tfstate'
              backendServiceArm: 'application-svc'
          - task: TerraformTask@5
            displayName: Terraform plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
              environmentServiceNameAzureRM: 'application-svc'
              commandOptions: '-var-file=terraform.tfvars -input=false -lock-timeout=300s'
  # - stage: manualvalidation
  #   dependsOn: terraformplan
  #   displayName: Manual Validation
  #   jobs:
  #     - job: manualvalidation
  #       displayName: manual validation
  #       pool: server
  #       steps:
  #         - task: ManualValidation@1
  #           inputs:
  #             notifyUsers: |
  #               brijesh@gmail.com
  #             instructions: 'Please approve to continue deployment'
              # onTimeout: 'reject'
  # - stage: Apply
  #   dependsOn: manualvalidation
  #   condition: succeeded()
  #   displayName: Apply
  #   jobs:            
  #     - job: apply
  #       displayName: Terraform Apply
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #       - task: TerraformTask@5
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'init'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
  #           backendAzureRmStorageAccountName: 'backendstg12354'
  #           backendAzureRmContainerName: 'my-container'
  #           backendAzureRmKey: 'raman-tfstate'
  #           backendServiceArm: 'application-svc'

  #       - task: TerraformTask@5
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'apply'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
  #           environmentServiceNameAzureRM: 'application-svc'
              




                  
                  
        