trigger:
  branches:
    include:
      - main

pool:
  name: newpool

stages:
  - stage: precheck
    displayName: "Terraform Validation"
    jobs:
      - job: terraformvalidate
        displayName: "Format & Validate"
        steps:
          - task: TerraformInstaller@1
            displayName: terraform install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: Terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'application-svc'
              backendAzureRmStorageAccountName: 'backendstg12354'
              backendAzureRmContainerName: 'my-container'
              backendAzureRmKey: 'raman-tfstate'
          - task: TerraformTask@5
            displayName: Terraform FMT
            inputs:
              provider: 'azurerm'
              command: 'custom'
              outputTo: 'console'
              customCommand: 'fmt'
              environmentServiceNameAzureRM: 'application-svc'
          - task: TerraformTask@5
            displayName: Terraform Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
      - job: tfsecurityscan
        dependsOn: terraformvalidate
        displayName: Security & Lint Scan
        continueOnError: true
        steps: 
          - task: tfsec@1
            displayName: tf_sec
            inputs:
              version: 'v1.26.0'
              dir: '$(Build.SourcesDirectory)/environments/dev'

          - script: |
              terraform init -backend=false
              tflint --init
              tflint --recursive
            displayName: Run TFLint
            workingDirectory: $(Build.SourcesDirectory)
            continueOnError: true
          - script: |
              python3 -m venv venv
              source venv/bin/activate
              pip install checkov
              checkov -d .
            workingDirectory: $(Build.SourcesDirectory)
      - job: infracostanalysis
        dependsOn: terraformvalidate
        displayName: "Infracost Analysis"
        steps:
          - script: |
              curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
              infracost breakdown --path .
            workingDirectory: $(Build.SourcesDirectory)
            env:
              INFRACOST_API_KEY: 'ico-ofRGrUGe9ncyiu9H0xRdqMsjihpJoXBl'
      



            
            
   